/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynightout.ui;

import javax.swing.JFrame;
import mynightout.controllers.DisplayCellarController;
import mynightout.entity.Cellar;

/**
 *
 * @author ioanna
 */
public class NightclubMainFrame extends javax.swing.JFrame {

    private String clubName;

    /**
     * Creates new form NightclubMainFrame
     */
    public NightclubMainFrame() {
        initComponents();
    }

    public NightclubMainFrame(String nightClubName) {
        clubName = nightClubName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clubNameLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        checkFullnessButton = new javax.swing.JButton();
        setDaysClosedButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        setClosedDatesButton = new javax.swing.JButton();
        showCellarForm = new javax.swing.JButton();
        showSuppliersButton = new javax.swing.JButton();
        displayCellarButton = new javax.swing.JButton();
        changeNightClubTableProfileButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(clubName.toString());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Διαχείρηση καταστήματος");

        clubNameLabel.setText("jLabel2");

        exitButton.setText("Κλείσιμο");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        checkFullnessButton.setText("Πληρότητα καταστήματος");
        checkFullnessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFullnessButtonActionPerformed(evt);
            }
        });

        setDaysClosedButton.setText("Μέρες κλειστό");
        setDaysClosedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDaysClosedButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Διαγραφή κράτησης");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        setClosedDatesButton.setText("Διάστημα κλειστό");
        setClosedDatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setClosedDatesButtonActionPerformed(evt);
            }
        });

        showCellarForm.setText("Εμφάνιση κελαριού");
        showCellarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCellarFormActionPerformed(evt);
            }
        });

        showSuppliersButton.setText("Εμφάνιση προμηθευτών");
        showSuppliersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSuppliersButtonActionPerformed(evt);
            }
        });

        displayCellarButton.setText("Εμφάνιση/επεξεργασία κάβας");
        displayCellarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCellarButtonActionPerformed(evt);
            }
        });

        changeNightClubTableProfileButton.setText("Αλλαγή στην κάτοψη");
        changeNightClubTableProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNightClubTableProfileButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Αποσύνδεση");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clubNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(changeNightClubTableProfileButton)
                                .addComponent(displayCellarButton)
                                .addComponent(setClosedDatesButton)
                                .addComponent(setDaysClosedButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkFullnessButton)
                                    .addComponent(deleteButton)
                                    .addComponent(showCellarForm)
                                    .addComponent(showSuppliersButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logOutButton)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubNameLabel)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showSuppliersButton)
                    .addComponent(changeNightClubTableProfileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCellarForm)
                    .addComponent(displayCellarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setClosedDatesButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setDaysClosedButton)
                    .addComponent(checkFullnessButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(logOutButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        clubNameLabel.setText(clubName);
    }//GEN-LAST:event_formWindowOpened

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void checkFullnessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFullnessButtonActionPerformed
        JFrame checkFullnessFrame = new CheckFullnessForm(clubName);
        this.dispose();
        checkFullnessFrame.setLocationRelativeTo(this);
        checkFullnessFrame.setVisible(true);
    }//GEN-LAST:event_checkFullnessButtonActionPerformed

    private void setDaysClosedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDaysClosedButtonActionPerformed
        SetNightClubDaysClosedForm sncdcf = new SetNightClubDaysClosedForm(clubName);
        this.dispose();
        sncdcf.setLocationRelativeTo(this);
        sncdcf.setVisible(true);
    }//GEN-LAST:event_setDaysClosedButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        JFrame deleteReservationFrame = new DeleteReservationForm(clubName);
        this.dispose();
        deleteReservationFrame.setLocationRelativeTo(this);
        deleteReservationFrame.setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void setClosedDatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setClosedDatesButtonActionPerformed
        SetNightClubClosedDatesForm snccdf = new SetNightClubClosedDatesForm(clubName);
        snccdf.setLocationRelativeTo(this);
        this.dispose();
        snccdf.setVisible(true);
    }//GEN-LAST:event_setClosedDatesButtonActionPerformed

    private void showCellarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCellarFormActionPerformed
        JFrame showCellarFrame = new ShowCellarForm(clubName);
        this.dispose();
        showCellarFrame.setLocationRelativeTo(this);
        showCellarFrame.setVisible(true);
    }//GEN-LAST:event_showCellarFormActionPerformed

    private void showSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSuppliersButtonActionPerformed
        JFrame showSuppliersFrame = new ShowSupplierForm(clubName);
        this.dispose();
        showSuppliersFrame.setLocationRelativeTo(this);
        showSuppliersFrame.setVisible(true);
    }//GEN-LAST:event_showSuppliersButtonActionPerformed

    private void displayCellarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCellarButtonActionPerformed
        String clubName = "Vogue";
        DisplayCellarController dcc = new DisplayCellarController();
        Cellar cellar = dcc.displayCellar(clubName);
        DisplayCellarForm dcf = new DisplayCellarForm(clubName);
        this.dispose();
        dcf.cellarTable.setValueAt(cellar.getVodka(), 0, 1);
        dcf.cellarTable.setValueAt(cellar.getWhiskey(), 1, 1);
        dcf.cellarTable.setValueAt(cellar.getWine(), 2, 1);
        dcf.cellarTable.setValueAt(cellar.getLiqueur(), 3, 1);
        dcf.cellarTable.setValueAt(cellar.getRum(), 4, 1);
        dcf.cellarTable.setValueAt(cellar.getTequila(), 5, 1);
        dcf.cellarTable.setValueAt(cellar.getBeer(), 6, 1);
        dcf.secretClubNameLabel.setText(clubName);
        dcf.setLocationRelativeTo(this);
        dcf.setVisible(true);
    }//GEN-LAST:event_displayCellarButtonActionPerformed

    private void changeNightClubTableProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNightClubTableProfileButtonActionPerformed
        this.dispose();
        ChangeNightClubTableProfileForm ctpf = new ChangeNightClubTableProfileForm(clubName);
        ctpf.setLocationRelativeTo(this);
        ctpf.setVisible(true);
    }//GEN-LAST:event_changeNightClubTableProfileButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        this.dispose();
        MainFrame mform = new MainFrame();
        mform.setLocationRelativeTo(this);
        mform.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NightclubMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NightclubMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NightclubMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NightclubMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NightclubMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeNightClubTableProfileButton;
    private javax.swing.JButton checkFullnessButton;
    private javax.swing.JLabel clubNameLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayCellarButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton setClosedDatesButton;
    private javax.swing.JButton setDaysClosedButton;
    private javax.swing.JButton showCellarForm;
    private javax.swing.JButton showSuppliersButton;
    // End of variables declaration//GEN-END:variables
}
