package mynightout.entity;
// Generated 17 NOV 2013 4:36:29 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

    private int reservationId;
    private int userId;
    private int clubId;
    private Date reservationDate;
    private int seatNumber;
    private String reservationStatus;
    //βοηθητικές μεταβλητές για τα test αυτά θα σταματήσουν να χρησιμοποιούνται
    //όταν γίνει η κανονική συνδεση με τη βαση.
        private String username;
        private boolean cancelSuccessful;
        private boolean successCreate;
    
    
    public Reservation() {
    }
    public Reservation(int clubId, Date reservationDate) {
        this.clubId = clubId;
        this.reservationDate = reservationDate;
    }

    public Reservation(String username, int reservationId) {
        this.username = username;
        this.reservationId = reservationId;
    }

    public Reservation(int reservationId) {
        this.reservationId = reservationId;
    }

    public Reservation(int userId, int clubId, Date reservationDate, int seatNumber) {
        this.userId = userId;
        this.clubId = clubId;
        this.reservationDate = reservationDate;
        this.seatNumber = seatNumber;
    }

    public Reservation(int userId, int clubId, Date reservationDate, int seatNumber, String reservationStatus) {
        this.userId = userId;
        this.clubId = clubId;
        this.reservationDate = reservationDate;
        this.seatNumber = seatNumber;
        this.reservationStatus = reservationStatus;
    }

    public boolean isSuccessCreate() {
        return successCreate;
    }

    public void setSuccessCreate(boolean successCreate) {
        this.successCreate = successCreate;
    }
    
    public boolean isCancelSuccessful() {
        return cancelSuccessful;
    }

    public void setCancelSuccessful(boolean cancelSuccessful) {
        this.cancelSuccessful = cancelSuccessful;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getReservationId() {
        return reservationId;
    }

    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getClubId() {
        return this.clubId;
    }

    public void setClubId(int clubId) {
        this.clubId = clubId;
    }

    public Date getReservationDate() {
        return this.reservationDate;
    }

    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }

    public int getSeatNumber() {
        return this.seatNumber;
    }

    public void setSeatNumber(int seatNumber) {
        this.seatNumber = seatNumber;
    }

    public String getReservationStatus() {
        return this.reservationStatus;
    }

    public void setReservationStatus(String reservationStatus) {
        this.reservationStatus = reservationStatus;
    }

}
