package mynightout.entity;
// Generated 4 DEC 2013 5:28:19 AM by Hibernate Tools 3.6.0



/**
 * Tables generated by hbm2java
 */
public class Tables  implements java.io.Serializable {


     private int clubId;
     private int firstRow;
     private int secondRow;
     private int thirdRow;
     private int fourthRow;
     private int fifthRow;
     private int sixthRow;

    public Tables() {
    }

    public Tables(int clubId, int firstRow, int secondRow, int thirdRow, int fourthRow, int fifthRow, int sixthRow) {
       this.clubId = clubId;
       this.firstRow = firstRow;
       this.secondRow = secondRow;
       this.thirdRow = thirdRow;
       this.fourthRow = fourthRow;
       this.fifthRow = fifthRow;
       this.sixthRow = sixthRow;
    }
   
    public int getClubId() {
        return this.clubId;
    }
    
    public void setClubId(int clubId) {
        this.clubId = clubId;
    }
    public int getFirstRow() {
        return this.firstRow;
    }
    
    public void setFirstRow(int firstRow) {
        this.firstRow = firstRow;
    }
    public int getSecondRow() {
        return this.secondRow;
    }
    
    public void setSecondRow(int secondRow) {
        this.secondRow = secondRow;
    }
    public int getThirdRow() {
        return this.thirdRow;
    }
    
    public void setThirdRow(int thirdRow) {
        this.thirdRow = thirdRow;
    }
    public int getFourthRow() {
        return this.fourthRow;
    }
    
    public void setFourthRow(int fourthRow) {
        this.fourthRow = fourthRow;
    }
    public int getFifthRow() {
        return this.fifthRow;
    }
    
    public void setFifthRow(int fifthRow) {
        this.fifthRow = fifthRow;
    }
    public int getSixthRow() {
        return this.sixthRow;
    }
    
    public void setSixthRow(int sixthRow) {
        this.sixthRow = sixthRow;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + this.clubId;
        hash = 61 * hash + this.firstRow;
        hash = 61 * hash + this.secondRow;
        hash = 61 * hash + this.thirdRow;
        hash = 61 * hash + this.fourthRow;
        hash = 61 * hash + this.fifthRow;
        hash = 61 * hash + this.sixthRow;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Tables other = (Tables) obj;
        if (this.clubId != other.clubId) {
            return false;
        }
        if (this.firstRow != other.firstRow) {
            return false;
        }
        if (this.secondRow != other.secondRow) {
            return false;
        }
        if (this.thirdRow != other.thirdRow) {
            return false;
        }
        if (this.fourthRow != other.fourthRow) {
            return false;
        }
        if (this.fifthRow != other.fifthRow) {
            return false;
        }
        if (this.sixthRow != other.sixthRow) {
            return false;
        }
        return true;
    }

    


}


