package mynightout.entity;
// Generated 4 DEC 2013 5:28:19 AM by Hibernate Tools 3.6.0

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer userId;
    private String username;
    private String password;
    private String customerName;
    private String customerLastname;
    private String telephoneNum;
    private String email;

    public User() {
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public User(String username, String password, String customerName, String customerLastname, String telephoneNum, String emailAddress) {
        this.username = username;
        this.password = password;
        this.customerName = customerName;
        this.customerLastname = customerLastname;
        this.telephoneNum = telephoneNum;
        this.email = emailAddress;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerLastname() {
        return this.customerLastname;
    }

    public void setCustomerLastname(String customerLastname) {
        this.customerLastname = customerLastname;
    }

    public String getTelephoneNum() {
        return this.telephoneNum;
    }

    public void setTelephoneNum(String telephoneNum) {
        this.telephoneNum = telephoneNum;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 73 * hash + (this.userId != null ? this.userId.hashCode() : 0);
        hash = 73 * hash + (this.username != null ? this.username.hashCode() : 0);
        hash = 73 * hash + (this.password != null ? this.password.hashCode() : 0);
        hash = 73 * hash + (this.customerName != null ? this.customerName.hashCode() : 0);
        hash = 73 * hash + (this.customerLastname != null ? this.customerLastname.hashCode() : 0);
        hash = 73 * hash + (this.telephoneNum != null ? this.telephoneNum.hashCode() : 0);
        hash = 73 * hash + (this.email != null ? this.email.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
    if (obj == null) {
    return false;
    }
    if (getClass() != obj.getClass()) {
    return false;
    }
    final User other = (User) obj;
    if (this.userId != other.userId && (this.userId == null || !this.userId.equals(other.userId))) {
    return false;
    }
    if ((this.username == null) ? (other.username != null) : !this.username.equals(other.username)) {
    return false;
    }
    if ((this.password == null) ? (other.password != null) : !this.password.equals(other.password)) {
    return false;
    }
    if ((this.customerName == null) ? (other.customerName != null) : !this.customerName.equals(other.customerName)) {
    return false;
    }
    if ((this.customerLastname == null) ? (other.customerLastname != null) : !this.customerLastname.equals(other.customerLastname)) {
    return false;
    }
    if ((this.telephoneNum == null) ? (other.telephoneNum != null) : !this.telephoneNum.equals(other.telephoneNum)) {
    return false;
    }
    if ((this.email == null) ? (other.email != null) : !this.email.equals(other.email)) {
    return false;
    }
    return true;
    }
    //@Override
    public boolean equalsForLogin(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final User other = (User) obj;
        if ((this.username == null) ? (other.username != null) : !this.username.equals(other.username)) {
            return false;
        }
        if ((this.password == null) ? (other.password != null) : !this.password.equals(other.password)) {
            return false;
        }
        return true;
    }
    
    

}
