package mynightout.entity;
// Generated 17 NOV 2013 4:36:29 PM by Hibernate Tools 3.6.0






/**
 * Nightclub generated by hbm2java
 */

public class Nightclub  implements java.io.Serializable {


     private int clubId;
     private String clubName;
     private String clubPassword;
     private int seatNumber;
     private String telephoneNum;

    public Nightclub() {
    }

    public Nightclub(String clubName, String clubPassword, int seatNumber, String telephoneNum) {
       this.clubName = clubName;
       this.clubPassword = clubPassword;
       this.seatNumber = seatNumber;
       this.telephoneNum = telephoneNum;
    }
   
    public Integer getClubId() {
        return this.clubId;
    }
    
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }
    public String getClubName() {
        return this.clubName;
    }
    
    public void setClubName(String clubName) {
        this.clubName = clubName;
    }
    public String getClubPassword() {
        return this.clubPassword;
    }
    
    public void setClubPassword(String clubPassword) {
        this.clubPassword = clubPassword;
    }
    public int getSeatNumber() {
        return this.seatNumber;
    }
    
    public void setSeatNumber(int seatNumber) {
        this.seatNumber = seatNumber;
    }
    public String getTelephoneNum() {
        return this.telephoneNum;
    }
    
    public void setTelephoneNum(String telephoneNum) {
        this.telephoneNum = telephoneNum;
    }




}


