package mynightout.entity;
// Generated 17 NOV 2013 4:36:29 PM by Hibernate Tools 3.6.0






/**
 * User generated by hbm2java
 */

public class User  implements java.io.Serializable {


     private int userId;
     private String username;
     private String password;
     private String customerName;
     private String customerLastname;
     private String telephoneNum;

    public User() {
    }

    public User(String username, String password, String customerName, String customerLastname, String telephoneNum) {
       this.username = username;
       this.password = password;
       this.customerName = customerName;
       this.customerLastname = customerLastname;
       this.telephoneNum = telephoneNum;
    }
   
    
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerLastname() {
        return this.customerLastname;
    }
    
    public void setCustomerLastname(String customerLastname) {
        this.customerLastname = customerLastname;
    }
    public String getTelephoneNum() {
        return this.telephoneNum;
    }
    
    public void setTelephoneNum(String telephoneNum) {
        this.telephoneNum = telephoneNum;
    }




}


