/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynightout.ui;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import mynightout.dao.TablesDao;
import mynightout.entity.Tables;
import mynightout.presenters.SelectTableProfilePresenter;

/**
 *
 * @author Dimitris
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelReservationButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        checkFullnessButton = new javax.swing.JButton();
        createStoreButton = new javax.swing.JButton();
        createReservationButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        faqButton = new javax.swing.JButton();
        showCellarForm = new javax.swing.JButton();
        showSuppliersButton = new javax.swing.JButton();
        changeNightClubTableProfileButton = new javax.swing.JButton();
        SelectTableButton = new javax.swing.JButton();
        confirmReservationButton = new javax.swing.JButton();
        setClosedDatesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyNightOut");

        cancelReservationButton.setText("Ακύρωση Κράτησης");
        cancelReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Κλείσιμο");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        checkFullnessButton.setText("Πληρότητα Καταστήματος");
        checkFullnessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFullnessButtonActionPerformed(evt);
            }
        });

        createStoreButton.setText("Δημιουργία Καταστήματος");
        createStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStoreButtonActionPerformed(evt);
            }
        });

        createReservationButton.setText("Δημιουργία Κράτησης");
        createReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReservationButtonActionPerformed(evt);
            }
        });

        editButton.setText("Επεξεργασία Κράτησης");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Διαγραφή Κράτησης");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        faqButton.setText("FAQ/Help");
        faqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faqButtonActionPerformed(evt);
            }
        });

        showCellarForm.setText("Εμφάνιση Κελαριού");
        showCellarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCellarFormActionPerformed(evt);
            }
        });

        showSuppliersButton.setText("Εμφάνιση Προμηθευτών");
        showSuppliersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSuppliersButtonActionPerformed(evt);
            }
        });

        changeNightClubTableProfileButton.setText("Αλλαγή στην κάτοψη");
        changeNightClubTableProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNightClubTableProfileButtonActionPerformed(evt);
            }
        });

        SelectTableButton.setText("Επιλογή τραπεζιού");
        SelectTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectTableButtonActionPerformed(evt);
            }
        });

        confirmReservationButton.setText("<html>Επιβεβαίωση των <br></br>\nστοιχειων της κράτησης</html>");
        confirmReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmReservationButtonActionPerformed(evt);
            }
        });

        setClosedDatesButton.setText("Διάστημα κλειστό");
        setClosedDatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setClosedDatesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setClosedDatesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(cancelReservationButton)
                                .addGap(5, 5, 5)
                                .addComponent(exitButton)
                                .addGap(5, 5, 5)
                                .addComponent(loginButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(checkFullnessButton)
                                .addGap(5, 5, 5)
                                .addComponent(createStoreButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(createReservationButton)
                                .addGap(5, 5, 5)
                                .addComponent(editButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(faqButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showCellarForm)
                                    .addComponent(showSuppliersButton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectTableButton)
                            .addComponent(changeNightClubTableProfileButton))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelReservationButton)
                    .addComponent(exitButton)
                    .addComponent(loginButton))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkFullnessButton)
                    .addComponent(createStoreButton))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createReservationButton)
                    .addComponent(editButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(faqButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCellarForm)
                    .addComponent(setClosedDatesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showSuppliersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeNightClubTableProfileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectTableButton))
                    .addComponent(confirmReservationButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationButtonActionPerformed
        // TODO add your handling code here:
        JFrame cancelBookFrame = new CancelBookForm();
        this.dispose();
        cancelBookFrame.setLocationRelativeTo(this);
        cancelBookFrame.setVisible(true);
    }//GEN-LAST:event_cancelReservationButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        JFrame loginFrame = new LoginForm();
        this.dispose();
        loginFrame.setLocationRelativeTo(this);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void checkFullnessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFullnessButtonActionPerformed
        // TODO add your handling code here:
        JFrame checkFullnessFrame = new CheckFullnessForm();
        this.dispose();
        checkFullnessFrame.setLocationRelativeTo(this);
        checkFullnessFrame.setVisible(true);
    }//GEN-LAST:event_checkFullnessButtonActionPerformed

    private void createReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReservationButtonActionPerformed

        JFrame createBookFrame = new CreateBookForm();
        dispose();
        createBookFrame.setLocationRelativeTo(this);
        createBookFrame.setVisible(true);

    }//GEN-LAST:event_createReservationButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
     JFrame editReservationFrame=new EditReservationForm();
     this.dispose();
     editReservationFrame.setLocationRelativeTo(this);
     editReservationFrame.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
     JFrame deleteReservationFrame=new DeleteReservationForm();
     this.dispose();
     deleteReservationFrame.setLocationRelativeTo(this);
     deleteReservationFrame.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void createStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStoreButtonActionPerformed
        // TODO add your handling code here:
        JFrame StoreRegisterForm = new StoreRegisterForm();
        this.dispose();
        StoreRegisterForm.setLocationRelativeTo(this);
        StoreRegisterForm.setVisible(true);
    }//GEN-LAST:event_createStoreButtonActionPerformed

    private void faqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faqButtonActionPerformed
        // TODO add your handling code here:
        JFrame contactAdminForm=new ContactAdminForm();
     
     contactAdminForm.setLocationRelativeTo(this);
     contactAdminForm.setVisible(true);
    }//GEN-LAST:event_faqButtonActionPerformed

    private void showCellarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCellarFormActionPerformed
      JFrame showCellarFrame=new ShowCellarForm();
      this.dispose();
      showCellarFrame.setLocationRelativeTo(this);
      showCellarFrame.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_showCellarFormActionPerformed

    private void showSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSuppliersButtonActionPerformed
      JFrame showSuppliersFrame=new ShowSupplierForm();
      this.dispose();
      showSuppliersFrame.setLocationRelativeTo(this);
      showSuppliersFrame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_showSuppliersButtonActionPerformed

    private void changeNightClubTableProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNightClubTableProfileButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChangeNightClubTableProfileForm ctpf=new ChangeNightClubTableProfileForm();
        ctpf.setLocationRelativeTo(this);
        ctpf.setVisible(true);
    }//GEN-LAST:event_changeNightClubTableProfileButtonActionPerformed

    private void SelectTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectTableButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SelectTableProfilePresenter stpp=new SelectTableProfilePresenter();
        int clubId=1;
        TablesDao td=new TablesDao();
        Tables t=td.getClubsTables("Vogue");
        try {
            stpp.showSelectTableProfile(new SelectTableProfileForm(), t.getFirstRow(), t.getSecondRow(), t.getThirdRow(), t.getFourthRow(), t.getFifthRow(), t.getSixthRow(), clubId);
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SelectTableButtonActionPerformed

    private void confirmReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmReservationButtonActionPerformed
        // TODO add your handling code here:
        ConfirmReservationInfoForm crif=new ConfirmReservationInfoForm();
        crif.customerLastNameLabel.setText("Λαλακίδης");
        crif.customerNameLabel.setText("Λαλάκης");
        crif.nightClubNameLabel.setText("Vogue");
        crif.reservationDateLabel.setText("01/01/2014");
        crif.reservationTableLabel.setText("Α3");
        this.dispose();
        crif.setVisible(true);
    }//GEN-LAST:event_confirmReservationButtonActionPerformed

    private void setClosedDatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setClosedDatesButtonActionPerformed
        // TODO add your handling code here:
        SetNightClubClosedDatesForm snccdf=new SetNightClubClosedDatesForm();
        snccdf.setLocationRelativeTo(this);
        this.dispose();
        snccdf.setVisible(true);
    }//GEN-LAST:event_setClosedDatesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectTableButton;
    private javax.swing.JButton cancelReservationButton;
    private javax.swing.JButton changeNightClubTableProfileButton;
    private javax.swing.JButton checkFullnessButton;
    private javax.swing.JButton confirmReservationButton;
    private javax.swing.JButton createReservationButton;
    private javax.swing.JButton createStoreButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton faqButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton setClosedDatesButton;
    private javax.swing.JButton showCellarForm;
    private javax.swing.JButton showSuppliersButton;
    // End of variables declaration//GEN-END:variables
}
