/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynightout.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import mynightout.dao.NightClubDao;
import mynightout.dao.ReservationDao;
import mynightout.dao.TablesDao;
import mynightout.entity.Reservation;
import mynightout.entity.Tables;
import mynightout.presenters.SelectTableProfilePresenter;

/**
 *
 * @author ioanna
 */
public class UserMainForm extends javax.swing.JFrame {

    private String currentUserName;

    /**
     * Creates new form UserMainForm
     */
    public UserMainForm() {
        initComponents();
    }

    public UserMainForm(String cUserName) {
        currentUserName = cUserName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        reservationEditButton = new javax.swing.JButton();
        cancelReservationButton = new javax.swing.JButton();
        createReservationButton = new javax.swing.JButton();
        confirmReservationButton = new javax.swing.JButton();
        showStoresButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        editUserInformationButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        userNameLabel.setText("jLabel1");

        reservationEditButton.setText("Επεξεργασία κράτησης");
        reservationEditButton.setEnabled(false);
        reservationEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationEditButtonActionPerformed(evt);
            }
        });

        cancelReservationButton.setText("Ακύρωση κράτησης");
        cancelReservationButton.setFocusPainted(false);
        cancelReservationButton.setFocusable(false);
        cancelReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationButtonActionPerformed(evt);
            }
        });

        createReservationButton.setText("Δημιουργία κράτησης");
        createReservationButton.setEnabled(false);
        createReservationButton.setFocusPainted(false);
        createReservationButton.setFocusable(false);
        createReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReservationButtonActionPerformed(evt);
            }
        });

        confirmReservationButton.setText("<html>Επιβεβαίωση των <br></br>\nστοιχειων της κράτησης</html>");
        confirmReservationButton.setEnabled(false);
        confirmReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmReservationButtonActionPerformed(evt);
            }
        });

        showStoresButton.setText("Προβολή καταστημάτων");
        showStoresButton.setFocusPainted(false);
        showStoresButton.setFocusable(false);
        showStoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStoresButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Αποσύνδεση");
        logOutButton.setFocusPainted(false);
        logOutButton.setFocusable(false);
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        editUserInformationButton.setText("Προβολή/επεξεργασία στοιχείων");
        editUserInformationButton.setFocusPainted(false);
        editUserInformationButton.setFocusable(false);
        editUserInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserInformationButtonActionPerformed(evt);
            }
        });

        jButton1.setText("View User's History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(userNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reservationEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createReservationButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelReservationButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(editUserInformationButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(showStoresButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(userNameLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservationEditButton)
                    .addComponent(createReservationButton))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showStoresButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(editUserInformationButton)
                .addGap(18, 18, 18)
                .addComponent(logOutButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        userNameLabel.setText(currentUserName);
    }//GEN-LAST:event_formWindowActivated

    private void reservationEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationEditButtonActionPerformed
        EditReservationForm editReservationFrame = new EditReservationForm(currentUserName);
        this.dispose();
        editReservationFrame.setLocationRelativeTo(this);
        editReservationFrame.setVisible(true);
    }//GEN-LAST:event_reservationEditButtonActionPerformed

    private void cancelReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationButtonActionPerformed
        CancelBookForm cancelBookFrame = new CancelBookForm(currentUserName);
        cancelBookFrame.userNameLabel.setText(currentUserName);
        this.dispose();
        ReservationDao reservation = new ReservationDao();
        List resultList = reservation.getUserReservations(currentUserName);
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Id κράτησης");
        tableHeaders.add("Club Name");
        tableHeaders.add("Reservation Date");
        tableHeaders.add("Τραπέζι");
        String DATE_FORMAT = "dd/MM/yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
        
        for (Object o : resultList) {
            Reservation res = (Reservation) o;
            Vector<Object> oneRow = new Vector<Object>();
            String clubName = new NightClubDao().getNightClubDataByClubId(res.getId().getClubId()).getClubName();
            oneRow.add(res.getId().getReservationId());
            oneRow.add(clubName);
            String reservationDate = sdf.format(res.getReservationDate());
            oneRow.add(reservationDate);
            oneRow.add(res.getTrapezi());
            tableData.add(oneRow);
        }
        cancelBookFrame.userReservationsTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        cancelBookFrame.setLocationRelativeTo(this);
        cancelBookFrame.setVisible(true);
    }//GEN-LAST:event_cancelReservationButtonActionPerformed

    private void createReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReservationButtonActionPerformed
        CreateBookForm createBookFrame = new CreateBookForm(currentUserName);
        this.dispose();
        createBookFrame.setLocationRelativeTo(this);
        createBookFrame.setVisible(true);
    }//GEN-LAST:event_createReservationButtonActionPerformed

    private void confirmReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmReservationButtonActionPerformed
        ConfirmReservationInfoForm crif = new ConfirmReservationInfoForm(currentUserName);
        crif.customerLastNameLabel.setText("Λαλακίδης");
        crif.customerNameLabel.setText("Λαλάκης");
        crif.nightClubNameLabel.setText("Vogue");
        crif.reservationDateLabel.setText("01/01/2014");
        crif.reservationTableLabel.setText("Α3");
        this.dispose();
        crif.setVisible(true);
    }//GEN-LAST:event_confirmReservationButtonActionPerformed

    private void showStoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStoresButtonActionPerformed
        StoresForm nightClubs = new StoresForm(currentUserName);
        this.dispose();
        nightClubs.setLocationRelativeTo(this);
        nightClubs.setVisible(true);
    }//GEN-LAST:event_showStoresButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        MainFrame mainFrame = new MainFrame();
        this.dispose();
        mainFrame.setLocationRelativeTo(this);
        mainFrame.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void editUserInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserInformationButtonActionPerformed
        EditUserInformationForm editUserInfoForm = new EditUserInformationForm(currentUserName);
        this.dispose();
        editUserInfoForm.setLocationRelativeTo(this);
        editUserInfoForm.setVisible(true);
    }//GEN-LAST:event_editUserInformationButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserHistoryForm userHistoryForm = new UserHistoryForm(currentUserName);
        userHistoryForm.userNameLabel.setText(currentUserName);
        this.dispose();
        ReservationDao reservation = new ReservationDao();
        List resultList = reservation.getUserReservations(currentUserName);
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Id κράτησης");
        tableHeaders.add("Club Name");
        tableHeaders.add("Reservation Date");
        tableHeaders.add("Τραπέζι");
        String DATE_FORMAT = "dd/MM/yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
        
        for (Object o : resultList) {
            Reservation res = (Reservation) o;
            Vector<Object> oneRow = new Vector<Object>();
            String clubName = new NightClubDao().getNightClubDataByClubId(res.getId().getClubId()).getClubName();
            oneRow.add(res.getId().getReservationId());
            oneRow.add(clubName);
            String reservationDate = sdf.format(res.getReservationDate());
            oneRow.add(reservationDate);
            oneRow.add(res.getTrapezi());
            tableData.add(oneRow);
        }
        userHistoryForm.userReservationsTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        userHistoryForm.setLocationRelativeTo(this);
        userHistoryForm.setVisible(true);
                                    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelReservationButton;
    private javax.swing.JButton confirmReservationButton;
    private javax.swing.JButton createReservationButton;
    private javax.swing.JButton editUserInformationButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton reservationEditButton;
    private javax.swing.JButton showStoresButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
