package mynightout.entity;
// Generated 4 DEC 2013 5:28:19 AM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Nightclub generated by hbm2java
 */
public class Nightclub implements java.io.Serializable {

    private Integer clubId;
    private String clubName;
    private String clubPassword;
    private String address;
    private String email;
    private String telephoneNum;
    private String category;
    private String clubImage;
    private Date closedFrom;
    private Date closedThrough;
    private String daysClosed;

    public Nightclub() {
    }

    public Nightclub(String clubName, String clubPassword) {
        this.clubName = clubName;
        this.clubPassword = clubPassword;
    }

    public Nightclub(String clubName, String clubPassword, String address,
            String emailAddress, String telephoneNum, String categoryId, String clubImage) {
        this.clubName = clubName;
        this.clubPassword = clubPassword;
        this.address = address;
        this.email = emailAddress;
        this.telephoneNum = telephoneNum;
        this.category = categoryId;
        this.clubImage = clubImage;

    }

    public Nightclub(Date closedFrom, Date closedThrough) {
        this.closedFrom = closedFrom;
        this.closedThrough = closedThrough;
    }

    public Nightclub(String daysClosed) {
        this.daysClosed = daysClosed;
    }

    public Integer getClubId() {
        return this.clubId;
    }

    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    public String getClubName() {
        return this.clubName;
    }

    public void setClubName(String clubName) {
        this.clubName = clubName;
    }

    public String getClubPassword() {
        return this.clubPassword;
    }

    public void setClubPassword(String clubPassword) {
        this.clubPassword = clubPassword;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelephoneNum() {
        return this.telephoneNum;
    }

    public void setTelephoneNum(String telephoneNum) {
        this.telephoneNum = telephoneNum;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getClubImage() {
        return this.clubImage;
    }

    public void setClubImage(String clubImage) {
        this.clubImage = clubImage;
    }

    public Date getClosedFrom() {
        return this.closedFrom;
    }

    public void setClosedFrom(Date closedFrom) {
        this.closedFrom = closedFrom;
    }

    public Date getClosedThrough() {
        return this.closedThrough;
    }

    public void setClosedThrough(Date closedThrough) {
        this.closedThrough = closedThrough;
    }

    public String getDaysClosed() {
        return this.daysClosed;
    }

    public void setDaysClosed(String daysClosed) {
        this.daysClosed = daysClosed;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.clubId != null ? this.clubId.hashCode() : 0);
        hash = 41 * hash + (this.clubName != null ? this.clubName.hashCode() : 0);
        hash = 41 * hash + (this.clubPassword != null ? this.clubPassword.hashCode() : 0);
        hash = 41 * hash + (this.address != null ? this.address.hashCode() : 0);
        hash = 41 * hash + (this.email != null ? this.email.hashCode() : 0);
        hash = 41 * hash + (this.telephoneNum != null ? this.telephoneNum.hashCode() : 0);
        hash = 41 * hash + (this.category != null ? this.category.hashCode() : 0);
        hash = 41 * hash + (this.clubImage != null ? this.clubImage.hashCode() : 0);
        hash = 41 * hash + (this.closedFrom != null ? this.closedFrom.hashCode() : 0);
        hash = 41 * hash + (this.closedThrough != null ? this.closedThrough.hashCode() : 0);
        hash = 41 * hash + (this.daysClosed != null ? this.daysClosed.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Nightclub other = (Nightclub) obj;
        if (this.clubId != other.clubId && (this.clubId == null || !this.clubId.equals(other.clubId))) {
            return false;
        }
        if ((this.clubName == null) ? (other.clubName != null) : !this.clubName.equals(other.clubName)) {
            return false;
        }
        if ((this.clubPassword == null) ? (other.clubPassword != null) : !this.clubPassword.equals(other.clubPassword)) {
            return false;
        }
        if ((this.address == null) ? (other.address != null) : !this.address.equals(other.address)) {
            return false;
        }
        if ((this.email == null) ? (other.email != null) : !this.email.equals(other.email)) {
            return false;
        }
        if ((this.telephoneNum == null) ? (other.telephoneNum != null) : !this.telephoneNum.equals(other.telephoneNum)) {
            return false;
        }
        if ((this.category == null) ? (other.category != null) : !this.category.equals(other.category)) {
            return false;
        }
        if ((this.clubImage == null) ? (other.clubImage != null) : !this.clubImage.equals(other.clubImage)) {
            return false;
        }
        if (this.closedFrom != other.closedFrom && (this.closedFrom == null || !this.closedFrom.equals(other.closedFrom))) {
            return false;
        }
        if (this.closedThrough != other.closedThrough && (this.closedThrough == null || !this.closedThrough.equals(other.closedThrough))) {
            return false;
        }
        if ((this.daysClosed == null) ? (other.daysClosed != null) : !this.daysClosed.equals(other.daysClosed)) {
            return false;
        }
        return true;
    }

    public boolean equalsForLogin(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Nightclub other = (Nightclub) obj;
        if ((this.clubName == null) ? (other.clubName != null) : !this.clubName.equals(other.clubName)) {
            return false;
        }
        if ((this.clubPassword == null) ? (other.clubPassword != null) : !this.clubPassword.equals(other.clubPassword)) {
            return false;
        }
        return true;
    }

}
