package mynightout.entity;
// Generated 4 DEC 2013 5:28:19 AM by Hibernate Tools 3.6.0



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private int supplierId;
     private String firstName;
     private String lastName;
     private String companyName;
     private String address;
     private String cellphoneNum;
     private String officephoneNum;
     private String emailAddress;

    public Supplier() {
    }

    public Supplier(int supplierId, String firstName, String lastName, 
            String companyName, String address, String cellphoneNum, 
            String officephoneNum, String emailAddress) {
       this.supplierId = supplierId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.companyName = companyName;
       this.address = address;
       this.cellphoneNum = cellphoneNum;
       this.officephoneNum = officephoneNum;
       this.emailAddress = emailAddress;
    }
   
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCellphoneNum() {
        return this.cellphoneNum;
    }
    
    public void setCellphoneNum(String cellphoneNum) {
        this.cellphoneNum = cellphoneNum;
    }
    public String getOfficephoneNum() {
        return this.officephoneNum;
    }
    
    public void setOfficephoneNum(String officephoneNum) {
        this.officephoneNum = officephoneNum;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }




}


