/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mynightout.ui;

/**
 *
 * @author Mustaine
 */
public class AlterStoreList extends javax.swing.JFrame {

    /**
     * Creates new form AlterStoreList
     */
    public AlterStoreList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AlterStore1 = new javax.swing.JButton();
        AlterStore2 = new javax.swing.JButton();
        AlterStore3 = new javax.swing.JButton();
        AlterStore4 = new javax.swing.JButton();
        AlterStore5 = new javax.swing.JButton();
        AlterStore6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Alternative");

        AlterStore1.setText("Κατάστημα1");
        AlterStore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterStore1ActionPerformed(evt);
            }
        });

        AlterStore2.setText("Κατάστημα2");
        AlterStore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterStore2ActionPerformed(evt);
            }
        });

        AlterStore3.setText("Κατάστημα3");
        AlterStore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterStore3ActionPerformed(evt);
            }
        });

        AlterStore4.setText("Κατάστημα4");
        AlterStore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterStore4ActionPerformed(evt);
            }
        });

        AlterStore5.setText("Κατάστημα5");
        AlterStore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterStore5ActionPerformed(evt);
            }
        });

        AlterStore6.setText("Κατάστημα6");
        AlterStore6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterStore6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AlterStore4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AlterStore1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AlterStore2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(AlterStore5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AlterStore3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(AlterStore6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(AlterStore1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlterStore3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlterStore2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AlterStore4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(AlterStore5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlterStore6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlterStore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterStore2ActionPerformed
        // TODO add your handling code here:
        StoreView SV = new StoreView();
        SV.setVisible(true);
        SV.StoreDesc.setText("Περιγραφη μαγαζιου 2");
    }//GEN-LAST:event_AlterStore2ActionPerformed

    private void AlterStore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterStore1ActionPerformed
        // TODO add your handling code here:
        StoreView SV = new StoreView();
        SV.setVisible(true);
        SV.StoreDesc.setText("Περιγραφη μαγαζιου 1");
    }//GEN-LAST:event_AlterStore1ActionPerformed

    private void AlterStore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterStore3ActionPerformed
        // TODO add your handling code here:
        StoreView SV = new StoreView();
        SV.setVisible(true);
        SV.StoreDesc.setText("Περιγραφη μαγαζιου 3");
    }//GEN-LAST:event_AlterStore3ActionPerformed

    private void AlterStore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterStore4ActionPerformed
        // TODO add your handling code here:
        StoreView SV = new StoreView();
        SV.setVisible(true);
        SV.StoreDesc.setText("Περιγραφη μαγαζιου 4");
    }//GEN-LAST:event_AlterStore4ActionPerformed

    private void AlterStore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterStore5ActionPerformed
        // TODO add your handling code here:
        StoreView SV = new StoreView();
        SV.setVisible(true);
        SV.StoreDesc.setText("Περιγραφη μαγαζιου 5");
    }//GEN-LAST:event_AlterStore5ActionPerformed

    private void AlterStore6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterStore6ActionPerformed
        // TODO add your handling code here:
        StoreView SV = new StoreView();
        SV.setVisible(true);
        SV.StoreDesc.setText("Περιγραφη μαγαζιου 6");
    }//GEN-LAST:event_AlterStore6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterStoreList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterStoreList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterStoreList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterStoreList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterStoreList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterStore1;
    private javax.swing.JButton AlterStore2;
    private javax.swing.JButton AlterStore3;
    private javax.swing.JButton AlterStore4;
    private javax.swing.JButton AlterStore5;
    private javax.swing.JButton AlterStore6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
