package mynightout.entity;
// Generated 4 DEC 2013 5:28:19 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private Date reservationDate;
     private String trapezi;
     private int seatNumber;
     private String reservationStatus;
     //βοηθητικές μεταβλητές για τα test αυτά θα σταματήσουν να χρησιμοποιούνται
    //όταν γίνει η κανονική συνδεση με τη βαση.
        private String username;
        private boolean cancelSuccessful;
        private boolean successCreate;
        private String clubName;

    public Reservation() {
    }
    
    public Reservation(ReservationId id, String username){
        this.id=id;
        this.username=username;
    }
    public Reservation(ReservationId id, Date reservationDate, 
            String trapezi, int seatNumber, String reservationStatus) {
       this.id = id;
       this.reservationDate = reservationDate;
       this.trapezi = trapezi;
       this.seatNumber = seatNumber;
       this.reservationStatus = reservationStatus;
    }

    public Reservation(ReservationId id) {
        this.id = id;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public Date getReservationDate() {
        return this.reservationDate;
    }
    
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }
    public String getTrapezi() {
        return this.trapezi;
    }
    
    public void setTrapezi(String trapezi) {
        this.trapezi = trapezi;
    }
    public int getSeatNumber() {
        return this.seatNumber;
    }
    
    public void setSeatNumber(int seatNumber) {
        this.seatNumber = seatNumber;
    }
    public String getReservationStatus() {
        return this.reservationStatus;
    }
    
    public void setReservationStatus(String reservationStatus) {
        this.reservationStatus = reservationStatus;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public boolean isCancelSuccessful() {
        return cancelSuccessful;
    }

    public void setCancelSuccessful(boolean cancelSuccessful) {
        this.cancelSuccessful = cancelSuccessful;
    }

    public boolean isSuccessCreate() {
        return successCreate;
    }

    public void setSuccessCreate(boolean successCreate) {
        this.successCreate = successCreate;
    }

    public String getClubName() {
        return clubName;
    }

    public void setClubName(String clubName) {
        this.clubName = clubName;
    }




}


