package mynightout.entity;
// Generated 4 DEC 2013 5:28:19 AM by Hibernate Tools 3.6.0



/**
 * Supply generated by hbm2java
 */
public class Supply  implements java.io.Serializable {


     private SupplyPk id;

    public Supply() {
    }

    public Supply(SupplyPk id) {
       this.id = id;
    }
   
    public SupplyPk getId() {
        return this.id;
    }
    
    public void setId(SupplyPk id) {
        this.id = id;
    }




}


