/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mynightout.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mynightout.controllers.UpdateCellarController;

/**
 *
 * @author Dimitris
 */
public class ConfirmUpdateCellarForm extends javax.swing.JFrame {
private String currentClubName;
    /**
     * Creates new form ConfirmUpdateCellarForm
     */
    public ConfirmUpdateCellarForm() {
        initComponents();
    }
public ConfirmUpdateCellarForm(String nightClubName) {
    currentClubName = nightClubName;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLabel = new javax.swing.JLabel();
        vodkaLabel = new javax.swing.JLabel();
        whiskeyLabel = new javax.swing.JLabel();
        wineLabel = new javax.swing.JLabel();
        liqueurLabel = new javax.swing.JLabel();
        rumLabel = new javax.swing.JLabel();
        tequilaLabel = new javax.swing.JLabel();
        beerLabel = new javax.swing.JLabel();
        vodkaValueLabel = new javax.swing.JLabel();
        whiskeyValueLabel = new javax.swing.JLabel();
        wineValueLabel = new javax.swing.JLabel();
        liqueurValueLabel = new javax.swing.JLabel();
        rumValueLabel = new javax.swing.JLabel();
        tequilaValueLabel = new javax.swing.JLabel();
        beerValueLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        clubNameLabel = new javax.swing.JLabel();
        nightClubNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageLabel.setText("Οι παρακάτω τιμές είναι σωστές;");

        vodkaLabel.setText("Vodka");

        whiskeyLabel.setText("Whiskey");

        wineLabel.setText("Wine");

        liqueurLabel.setText("Liqueur");

        rumLabel.setText("Rum");

        tequilaLabel.setText("Tequila");

        beerLabel.setText("Beer");

        vodkaValueLabel.setText("jLabel1");

        whiskeyValueLabel.setText("jLabel2");

        wineValueLabel.setText("jLabel3");

        liqueurValueLabel.setText("jLabel4");

        rumValueLabel.setText("jLabel5");

        tequilaValueLabel.setText("jLabel6");

        beerValueLabel.setText("jLabel7");

        yesButton.setText("Ναι");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("Όχι");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        clubNameLabel.setText("Όνομα καταστήματος:");

        nightClubNameLabel.setText("NightClubName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(messageLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(whiskeyLabel)
                            .addComponent(vodkaLabel)
                            .addComponent(wineLabel)
                            .addComponent(liqueurLabel)
                            .addComponent(rumLabel)
                            .addComponent(tequilaLabel)
                            .addComponent(beerLabel)
                            .addComponent(yesButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vodkaValueLabel)
                            .addComponent(whiskeyValueLabel)
                            .addComponent(wineValueLabel)
                            .addComponent(liqueurValueLabel)
                            .addComponent(rumValueLabel)
                            .addComponent(tequilaValueLabel)
                            .addComponent(beerValueLabel)
                            .addComponent(noButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clubNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nightClubNameLabel)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubNameLabel)
                    .addComponent(nightClubNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vodkaLabel)
                    .addComponent(vodkaValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiskeyLabel)
                    .addComponent(whiskeyValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wineLabel)
                    .addComponent(wineValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liqueurLabel)
                    .addComponent(liqueurValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rumLabel)
                    .addComponent(rumValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tequilaLabel)
                    .addComponent(tequilaValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beerLabel)
                    .addComponent(beerValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed

        this.dispose();
        DisplayCellarForm dcf=new DisplayCellarForm(currentClubName);
        dcf.cellarTable.setValueAt(vodkaValueLabel.getText(), 0, 1);
        dcf.cellarTable.setValueAt(whiskeyValueLabel.getText(), 1, 1);
        dcf.cellarTable.setValueAt(wineValueLabel.getText(), 2, 1);
        dcf.cellarTable.setValueAt(liqueurValueLabel.getText(), 3, 1);
        dcf.cellarTable.setValueAt(rumValueLabel.getText(), 4, 1);
        dcf.cellarTable.setValueAt(tequilaValueLabel.getText(), 5, 1);
        dcf.cellarTable.setValueAt(beerValueLabel.getText(), 6, 1);
        dcf.secretClubNameLabel.setText(nightClubNameLabel.getText());
        dcf.setLocationRelativeTo(this);
        dcf.setVisible(true);
        
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
        UpdateCellarController ucc=new UpdateCellarController();
        
        try{        
            ucc.updateCellar(nightClubNameLabel.getText(), Integer.parseInt(vodkaValueLabel.getText()), Integer.parseInt(whiskeyValueLabel.getText()), Integer.parseInt(wineValueLabel.getText()), Integer.parseInt(liqueurValueLabel.getText()), Integer.parseInt(rumValueLabel.getText()), Integer.parseInt(tequilaValueLabel.getText()), Integer.parseInt(beerValueLabel.getText()));
            JOptionPane.showMessageDialog(null, "Η ενημέρωση έγινε με επιτυχία.", "Success",JOptionPane.INFORMATION_MESSAGE);
            JFrame mainNightClubFrame=new NightclubMainForm(currentClubName);
            this.dispose();
            mainNightClubFrame.setLocationRelativeTo(this);
            mainNightClubFrame.setVisible(true);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Failure",JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_yesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmUpdateCellarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmUpdateCellarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmUpdateCellarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmUpdateCellarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmUpdateCellarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beerLabel;
    public javax.swing.JLabel beerValueLabel;
    private javax.swing.JLabel clubNameLabel;
    private javax.swing.JLabel liqueurLabel;
    public javax.swing.JLabel liqueurValueLabel;
    private javax.swing.JLabel messageLabel;
    public javax.swing.JLabel nightClubNameLabel;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel rumLabel;
    public javax.swing.JLabel rumValueLabel;
    private javax.swing.JLabel tequilaLabel;
    public javax.swing.JLabel tequilaValueLabel;
    private javax.swing.JLabel vodkaLabel;
    public javax.swing.JLabel vodkaValueLabel;
    private javax.swing.JLabel whiskeyLabel;
    public javax.swing.JLabel whiskeyValueLabel;
    private javax.swing.JLabel wineLabel;
    public javax.swing.JLabel wineValueLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
